AWSTemplateFormatVersion: '2010-09-09'
Description: 'CloudFormation stack for the LINE Bot Chart Generator API'

Resources:
  # S3 Bucket to store generated chart images
  ImageBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub 'line-bot-images-${AWS::StackName}-${AWS::AccountId}'
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      CorsConfiguration:
        CorsRules:
          - AllowedHeaders:
              - '*'
            AllowedMethods:
              - GET
            AllowedOrigins:
              - '*'
            MaxAge: 3600

  # IAM Role for the Lambda function
  LambdaExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
      Policies:
        - PolicyName: S3WritePolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - s3:PutObject
                  - s3:PutObjectAcl
                Resource: !Sub 'arn:aws:s3:::${ImageBucket}/*'

  # Lambda Function to generate charts
  GenerateChartFunction:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: !Sub '${AWS::StackName}-GenerateChartFunction'
      Handler: index.handler
      Runtime: nodejs20.x
      Role: !GetAtt LambdaExecutionRole.Arn
      Code:
        S3Bucket: '2025-aws-educate-tw-n8n-workshop-bucket'
        S3Key: 'generate_chart.zip'
      Environment:
        Variables:
          BUCKET_NAME: !Ref ImageBucket
          CHART_PAGE_URL: 'http://2025-aws-educate-tw-n8n-workshop-bucket.s3-website-us-east-1.amazonaws.com'
      Timeout: 30

  # HTTP API Gateway
  HttpApi:
    Type: AWS::ApiGatewayV2::Api
    Properties:
      Name: !Sub '${AWS::StackName}-ChartApi'
      ProtocolType: HTTP
      CorsConfiguration:
        AllowOrigins:
          - '*'
        AllowMethods:
          - POST
          - GET
        AllowHeaders:
          - '*'

  # API Gateway Integration with Lambda
  LambdaIntegration:
    Type: AWS::ApiGatewayV2::Integration
    Properties:
      ApiId: !Ref HttpApi
      IntegrationType: AWS_PROXY
      IntegrationUri: !GetAtt GenerateChartFunction.Arn
      PayloadFormatVersion: '2.0'

  # API Gateway Route for POST requests
  ApiRoute:
    Type: AWS::ApiGatewayV2::Route
    Properties:
      ApiId: !Ref HttpApi
      RouteKey: 'POST /'
      Target: !Join ['/', ['integrations', !Ref LambdaIntegration]]

  # API Gateway Default Stage
  ApiStage:
    Type: AWS::ApiGatewayV2::Stage
    Properties:
      ApiId: !Ref HttpApi
      StageName: $default
      AutoDeploy: true

  # Permission for API Gateway to invoke Lambda
  LambdaApiPermission:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !GetAtt GenerateChartFunction.Arn
      Action: lambda:InvokeFunction
      Principal: apigateway.amazonaws.com
      SourceArn: !Sub 'arn:${AWS::Partition}:execute-api:${AWS::Region}:${AWS::AccountId}:${HttpApi}/*'

Outputs:
  ApiEndpoint:
    Description: "The endpoint URL for the Chart Generator API"
    Value: !GetAtt HttpApi.ApiEndpoint
  ImageBucketName:
    Description: "Name of the S3 bucket for storing generated images"
    Value: !Sub 'line-bot-images-${AWS::StackName}-${AWS::AccountId}'
